### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by yamamoto-yuta** [RibbonCMS/RibbonCMS.github.io#2]
```yaml
blog_title: Simple Blog Template
site_introduction: This is template of RibbonCMS
copylight_name: ShotaroKataoka
copylight_url: https://github.com/ShotaroKataoka
root_url: https://ribboncms.github.io
issues_page_url: https://github.com/RibbonCMS/RibbonCMS.github.io/issues
favicon_image_url: https://user-images.githubusercontent.com/42331656/175183205-06dc6033-af20-44b9-ae3d-c3e68770a1f3.png
author_name: RibbonCMS team
author_introduction: We are RibbonCMS team.
avatar_image_url: https://user-images.githubusercontent.com/42331656/175183205-06dc6033-af20-44b9-ae3d-c3e68770a1f3.png
sns:
  - name: GitHub
    url: 
#  - name: Twitter
#    url: 
#  - name: Facebook
#    url: 
#  - name: LinkedIn
#    url: 
#  - name: Instagram
#    url: 
#  - name: Youtube
#    url: 
```
